with open("services/telegram_bot.py", "r", encoding="utf-8") as f:
    text = f.read()

import re
pattern = r'def notify_sim_trade\(symbol: str, action.*?return send_telegram_message\(text\)'
text = re.sub(pattern, lambda m: "", text, flags=re.DOTALL)

with open("services/telegram_bot.py", "w", encoding="utf-8") as f:
    f.write(text.strip() + "\n\n")
    f.write("def notify_sim_trade(symbol: str, action: str, price: float, pnl_pct: float = 0.0, reason: str = \"\", date_str: str = \"\", trade: dict = None) -> bool:\n")
    f.write("    import json, os\n")
    f.write("    from datetime import datetime\n")
    f.write("    if not date_str:\n")
    f.write("        date_str = datetime.now().strftime(\"%Y-%m-%d\")\n")
    f.write("        \n")
    f.write("    cache_file = \"data/sent_sim_alerts.json\"\n")
    f.write("    cache = {}\n")
    f.write("    if os.path.exists(cache_file):\n")
    f.write("        try:\n")
    f.write("            with open(cache_file, \"r\", encoding=\"utf-8\") as f_c:\n")
    f.write("                cache = json.load(f_c)\n")
    f.write("        except:\n")
    f.write("            pass\n")
    f.write("            \n")
    f.write("    if cache.get(\"date\") != date_str:\n")
    f.write("        cache = {\"date\": date_str, \"alerts\": []}\n")
    f.write("        \n")
    f.write("    alert_key = f\"{symbol}_{action}_{price:.2f}\"\n")
    f.write("    if alert_key in cache[\"alerts\"]:\n")
    f.write("        return True\n")
    f.write("        \n")
    f.write("    cache[\"alerts\"].append(alert_key)\n")
    f.write("    try:\n")
    f.write("        with open(cache_file, \"w\", encoding=\"utf-8\") as f_c:\n")
    f.write("            json.dump(cache, f_c)\n")
    f.write("    except:\n")
    f.write("        pass\n")
    f.write("        \n")
    f.write("    trade = trade or {}\n")
    f.write("    shares = trade.get('shares', 0)\n")
    f.write("    total_val = shares * price if shares else 0\n")
    f.write("    tp1 = trade.get('tp1_price', 0)\n")
    f.write("    sl = trade.get('stop_price', 0)\n")
    f.write("    entry = trade.get('entry_price', price)\n")
    f.write("    \n")
    f.write("    tp_pct = ((tp1 - entry) / entry * 100) if tp1 and entry else 0\n")
    f.write("    sl_pct = ((entry - sl) / entry * 100) if sl and entry else 0\n")
    f.write("    \n")
    f.write("    if \"AL\" in action:\n")
    f.write("        text = \"\U0001F916 <b>SIMULASYON \" + action + \"</b>\\n\\n\"\n")
    f.write("        text += \"\U0001F4C8 <b>\" + symbol + \"</b> ? \" + f\"{price:.2f}\" + \" TL\\n\"\n")
    f.write("        text += \"\U0001F4E6 <b>Lot Sayisi:</b> \" + str(shares) + \" Lot\\n\"\n")
    f.write("        text += \"\U0001F4B0 <b>Toplam Tutar:</b> \" + f\"{total_val:.2f}\" + \" TL\\n\\n\"\n")
    f.write("        text += \"\U0001F3AF <b>Kar Al (TP):</b> \" + f\"{tp1:.2f}\" + \" TL (+%\" + f\"{tp_pct:.1f}\" + \")\\n\"\n")
    f.write("        text += \"\U0001F6D1 <b>Stop Sat (SL):</b> \" + f\"{sl:.2f}\" + \" TL (-%\" + f\"{sl_pct:.1f}\" + \")\\n\"\n")
    f.write("        if reason:\n")
    f.write("            text += \"\\n\U0001F4A1 <b>Neden:</b> \" + reason\n")
    f.write("        return send_telegram_message(text)\n")
    f.write("    else:\n")
    f.write("        emoji = \"\U0001F7E2\" if pnl_pct >= 0 else \"\U0001F534\"\n")
    f.write("        pnl_val = trade.get('pnl_val', 0)\n")
    f.write("        text = \"\U0001F916 <b>SIMULASYON \" + action + \"</b>\\n\\n\"\n")
    f.write("        text += \"\U0001F4C9 <b>\" + symbol + \"</b> ? \" + f\"{price:.2f}\" + \" TL\\n\"\n")
    f.write("        text += \"\U0001F4E6 <b>Lot Sayisi:</b> \" + str(shares) + \" Lot\\n\"\n")
    f.write("        text += \"\U0001F4B0 <b>Cikis Tutari:</b> \" + f\"{total_val:.2f}\" + \" TL\\n\\n\"\n")
    f.write("        text += emoji + \" <b>K/Z (Tutar):</b> \" + f\"{pnl_val:+.2f}\" + \" TL\\n\"\n")
    f.write("        text += emoji + \" <b>K/Z (%):</b> %\" + f\"{pnl_pct:+.2f}\" + \"\\n\"\n")
    f.write("        if reason:\n")
    f.write("            text += \"\\n\U0001F4A1 <b>Neden:</b> \" + reason\n")
    f.write("        return send_telegram_message(text)\n")

print("FIX FINAL OK")
