with open("services/telegram_bot.py", "a", encoding="utf-8") as f:
    f.write("\n")
    f.write("def notify_sim_trade(symbol: str, action: str, price: float, pnl_pct: float = 0.0, reason: str = \"\", date_str: str = \"\") -> bool:\n")
    f.write("    import json, os\n")
    f.write("    from datetime import datetime\n")
    f.write("    if not date_str:\n")
    f.write("        date_str = datetime.now().strftime(\"%Y-%m-%d\")\n")
    f.write("    cache_file = \"data/sent_sim_alerts.json\"\n")
    f.write("    cache = {}\n")
    f.write("    if os.path.exists(cache_file):\n")
    f.write("        try:\n")
    f.write("            with open(cache_file, \"r\", encoding=\"utf-8\") as f_c:\n")
    f.write("                cache = json.load(f_c)\n")
    f.write("        except:\n")
    f.write("            pass\n")
    f.write("    if cache.get(\"date\") != date_str:\n")
    f.write("        cache = {\"date\": date_str, \"alerts\": []}\n")
    f.write("    alert_key = f\"{symbol}_{action}_{price:.2f}\"\n")
    f.write("    if alert_key in cache[\"alerts\"]:\n")
    f.write("        return True\n")
    f.write("    cache[\"alerts\"].append(alert_key)\n")
    f.write("    try:\n")
    f.write("        with open(cache_file, \"w\", encoding=\"utf-8\") as f_c:\n")
    f.write("            json.dump(cache, f_c)\n")
    f.write("    except:\n")
    f.write("        pass\n")
    f.write("    if \"AL\" in action:\n")
    f.write("        text = (f\"\U0001F916 <b>SIMULASYON {action}</b>\\n\" + f\"\U0001F4C8 {symbol} -> {price:.2f} TL\\n\")\n")
    f.write("        if reason:\n")
    f.write("            text += f\"\U0001F4A1 Neden: {reason}\"\n")
    f.write("        return send_telegram_message(text)\n")
    f.write("    else:\n")
    f.write("        emoji = \"\U0001F7E2\" if pnl_pct >= 0 else \"\U0001F534\"\n")
    f.write("        text = (f\"\U0001F916 <b>SIMULASYON {action}</b>\\n\" + f\"\U0001F4C9 {symbol} -> {price:.2f} TL\\n\" + f\"{emoji} K/Z: %{pnl_pct:+.2f}\\n\")\n")
    f.write("        if reason:\n")
    f.write("            text += f\"\U0001F4A1 Neden: {reason}\"\n")
    f.write("        return send_telegram_message(text)\n")

print("TELEGRAM PATCH SAFE OK")
